#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Border
bspc config normal_border_color "#000000"
bspc config focused_border_color "#797979"
bspc config active_border_color  "#073642"
bspc config presel_feedback_color "#797979"

~/.config/bspwm/scripts/autostart
