#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config pointer_follows_focus true
#bspc config focus_follows_pointer true

# Border

bspc config normal_border_color   "#000000"
bspc config focused_border_color  "#777777"



#
# Autostart
#

~/.config/bspwm/scripts/autostart
