#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

##############
#Monitor
#############
bspc monitor -d 1 2 3 4 5 

###############
#Config
###############
bspc config border_width         2
bspc config window_gap           3
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#################
# padding 
#################
bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

#################
#Rules
################


##################
# Border
##################

#. "${HOME}/.cache/wal/colors.sh"
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"


$HOME/.config/bspwm/scripts/autostart
