#! /bin/sh

###################
# Autostart
###################
#keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
polybar &		 


# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
feh --bg-fill ~/.local/share/backgrounds/yourname.png    

# Dex
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom A
picom -b 


# Network Applet
#nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

############
#Fixed
###########
#Java WM fix
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
wmname LG3D


##############
#Monitor
#############
bspc monitor -d I II III IV V 

###############
#Config
###############
bspc config border_width         2
bspc config window_gap           2
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#################
#Rules
################

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Yad state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


#################
# padding 
#################
bspc config top_padding 19
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0


##################
# Border
##################
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
