#! /bin/sh

picom &

/usr/bin/dunst &

feh --bg-fill $HOME/.local/share/backgrounds/arch.png 

$HOME/.config/polybar/launch &

$HOME/.config/bspwm/scripts/low_bat_notifier.sh

$HOME/.config/bspwm/scripts/battery_notifier.sh


